// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tcrdist_cpp
NumericMatrix tcrdist_cpp(const IntegerMatrix& all_mat1, const IntegerMatrix& all_mat2, const IntegerMatrix& submat, const bool tcr2_equals_tcr1);
RcppExport SEXP _TIRTLtools_tcrdist_cpp(SEXP all_mat1SEXP, SEXP all_mat2SEXP, SEXP submatSEXP, SEXP tcr2_equals_tcr1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type all_mat1(all_mat1SEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type all_mat2(all_mat2SEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type submat(submatSEXP);
    Rcpp::traits::input_parameter< const bool >::type tcr2_equals_tcr1(tcr2_equals_tcr1SEXP);
    rcpp_result_gen = Rcpp::wrap(tcrdist_cpp(all_mat1, all_mat2, submat, tcr2_equals_tcr1));
    return rcpp_result_gen;
END_RCPP
}
// tcrdist_parallel
NumericMatrix tcrdist_parallel(const IntegerMatrix& all_mat1, const IntegerMatrix& all_mat2, const NumericMatrix& submat, const bool tcr2_equals_tcr1);
RcppExport SEXP _TIRTLtools_tcrdist_parallel(SEXP all_mat1SEXP, SEXP all_mat2SEXP, SEXP submatSEXP, SEXP tcr2_equals_tcr1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type all_mat1(all_mat1SEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type all_mat2(all_mat2SEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type submat(submatSEXP);
    Rcpp::traits::input_parameter< const bool >::type tcr2_equals_tcr1(tcr2_equals_tcr1SEXP);
    rcpp_result_gen = Rcpp::wrap(tcrdist_parallel(all_mat1, all_mat2, submat, tcr2_equals_tcr1));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TIRTLtools_tcrdist_cpp", (DL_FUNC) &_TIRTLtools_tcrdist_cpp, 4},
    {"_TIRTLtools_tcrdist_parallel", (DL_FUNC) &_TIRTLtools_tcrdist_parallel, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TIRTLtools(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
